CREATE TABLE `_tblRuleConfig` (
  `intRuleConfigID` int(11) NOT NULL AUTO_INCREMENT,
  `intRealmID` int(11) NOT NULL DEFAULT '0',
  `intSubRealmID` int(11) NOT NULL DEFAULT '0',
  `intOriginLevel` int(11) DEFAULT '0',
  `strWFRuleFor` varchar(30) DEFAULT '' COMMENT 'PERSON, REGO, ENTITY, DOCUMENT',
  `strEntityType` varchar(30) DEFAULT '',
  `intEntityLevel` int(11) DEFAULT '0',
  `strRegistrationNature` varchar(20) NOT NULL DEFAULT '0' COMMENT 'NEW,RENEWAL,AMENDMENT,TRANSFER,',
  `strPersonType` varchar(20) NOT NULL DEFAULT '' COMMENT 'PLAYER, COACH, REFEREE',
  `strPersonLevel` varchar(20) NOT NULL DEFAULT '' COMMENT 'AMATEUR,PROFESSIONAL',
  `strSport` varchar(20) NOT NULL DEFAULT '' COMMENT 'FOOTBALL,FUTSAL,BEACHSOCCER',
  `strAgeLevel` varchar(20) NOT NULL DEFAULT '' COMMENT 'SENIOR,JUNIOR',
  `intApprovalEntityLevel` int(11) NOT NULL DEFAULT '0' COMMENT 'Which Entity level has to approve this rule',
  `intProblemResolutionEntityLevel` int(11) NOT NULL DEFAULT '0' COMMENT 'Which Entity Level to solve issues',
  `strTaskType` varchar(20) NOT NULL DEFAULT 'APPROVAL' COMMENT 'APPROVAL,DOCUMENT',
  `strTaskStatus` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING,ACTIVE',
  `tTimeStamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `intDocumentTypeID` int(11) DEFAULT '0',
  `intRemoveTaskOnPayment` tinyint(4) DEFAULT '0' COMMENT 'On Payment, remove task and either go to next one or approve person/Rego/Entity',
  `intLockTaskUntilGatewayResponse` tinyint(4) DEFAULT '0' COMMENT 'Locks task until response from gateway',
  `intLockTaskUntilPaid` tinyint(4) DEFAULT '0' COMMENT 'Locks task until paid',
  `intAutoActivateOnPayment` tinyint(4) DEFAULT '0' COMMENT 'Auto Activate Person/Rego on Payment',
  `strPersonEntityRole` varchar(50) DEFAULT '',
  `strISOCountry_IN` varchar(200) DEFAULT '',
  `strISOCountry_NOTIN` varchar(200) DEFAULT '',
  `intNeededITC` tinyint(4) DEFAULT '0' COMMENT 'Was an ITC needed',
  `intUsingITCFilter` tinyint(4) DEFAULT '0' COMMENT 'Using ITC filter',
  `intCopiedFromRuleID` int(11) DEFAULT '0' COMMENT 'The ID of the rule this record was copied from - used for tblWFRuleDocument setup',
  `intUsingPersonLevelChangeFilter` tinyint(4) DEFAULT '0' COMMENT 'Using Person Level change filter',
  `intPersonLevelChange` tinyint(4) DEFAULT '0' COMMENT 'Was Person Level changed',
  PRIMARY KEY (`intRuleConfigID`),
  KEY `index_intRealmID` (`intRealmID`,`intSubRealmID`),
  KEY `index_RuleFor` (`strWFRuleFor`),
  KEY `index_strPersonType` (`strPersonType`),
  KEY `index_intOriginLevel` (`intOriginLevel`),
  KEY `index_strRegistrationNature` (`strRegistrationNature`)
) ENGINE=InnoDB AUTO_INCREMENT=2889 DEFAULT CHARSET=utf8 COMMENT='Defines the flow of approvals for a registration. One set of rules per Realm. Within Realm there is one row for each combination of PersonType, Level, Sport, Nature, AgeLevel';
