DROP TABLE tblClearanceHoldingBay;
#
CREATE table tblClearanceHoldingBay (
	intHoldingBayID    				INT NOT NULL AUTO_INCREMENT,
	intClearanceID                  INT(11) DEFAULT 0,
	intRequestLevelID               INT(11) DEFAULT 0,
	intRequestID                    INT(11) DEFAULT 0,
	intRealmID			            INT(11) DEFAULT 0,
	intDestinationClubID			INT(11) DEFAULT 0,
	intDestinationAssocID			INT(11) DEFAULT 0,
	intDestinationInternationalLevelID		    INT(11) NOT NULL DEFAULT 0,
	intDestinationInternationalID		        INT(11) NOT NULL DEFAULT 0,
    intHoldingBayStatus             TINYINT DEFAULT 0,
    strWhyDenied                    TEXT,
	intMemberID		                INT(11) NOT NULL DEFAULT 0,
    strFirstname                    VARCHAR(50) DEFAULT '',
    strSurname                      VARCHAR(50) DEFAULT '',
    strMemberNo                     VARCHAR(50) DEFAULT '',
    strNationalNum                  VARCHAR(30) DEFAULT '',
    strPassportNationality          VARCHAR(50) DEFAULT '',
    dtDOB                           DATE,
    intGender                       TINYINT,
    intHasAgent                     TINYINT,
    strAgentFirstname               VARCHAR(50) DEFAULT '',
    strAgentSurname                 VARCHAR(50) DEFAULT '',
    strAgentNationality             VARCHAR(50) DEFAULT '',
    strAgentLicenseNum              VARCHAR(50) DEFAULT '',
    strAgencyName                    VARCHAR(150) DEFAULT '',
    strAgencyEmail                   VARCHAR(100) DEFAULT '',
	dtApplied			            DATETIME,
	tTimeStamp			            TIMESTAMP,
	strReasonForClearance		    TEXT,
	strOtherNotes	                TEXT,
	intClearanceStatus		        INTEGER,
	intReasonForClearanceID         INT(11) DEFAULT 0,
	strFilingNumber	                varchar(20) default '',
	intClearancePriority            INT(11) DEFAULT 0,
	intRecStatus	                INT(11) DEFAULT 0,
	intPlayerActive                 tinyint DEFAULT 0,
    intCoachActive                  tinyint DEFAULT 0,
    intMthOfficialActive            tinyint DEFAULT 0,
    intPermitType                   INT DEFAULT 0,
	dtPermitFrom	                DATETIME,
	dtPermitTo	                    DATETIME,
    intClearanceYear                INT DEFAULT 0,

PRIMARY KEY (intHoldingBayID),
	KEY index_intDestinationInternationalLevelID(intDestinationInternationalLevelID),
	KEY index_intDestinationInternationalID(intDestinationInternationalID),
	KEY index_intMemberID(intMemberID),
	KEY index_intDestinationClubID(intDestinationClubID),
	KEY index_intDestinationAssocID(intDestinationAssocID),
	KEY index_intRealmID(intRealmID),
	KEY index_intClearanceStatus(intClearanceStatus)
);
 
