DROP TABLE tblClearance;

CREATE TABLE `tblClearance` (
  `intClearanceID` int(11) NOT NULL AUTO_INCREMENT,
  `intPersonID` int(11) NOT NULL DEFAULT '0',
  `intDestinationEntityID` int(11) NOT NULL DEFAULT '0',
  `strDestinationEntityName` varchar(100) DEFAULT NULL,
  `intSourceEntityID` int(11) NOT NULL DEFAULT '0',
  `strSourceEntityName` varchar(100) DEFAULT NULL,
  `intDestinationAssocID` int(11) NOT NULL DEFAULT '0',
  `strDestinationAssocName` varchar(100) DEFAULT NULL,
  `intSourceAssocID` int(11) NOT NULL DEFAULT '0',
  `strSourceAssocName` varchar(100) DEFAULT NULL,
  `intRealmID` int(11) NOT NULL DEFAULT '0',
  `intCurrentPathID` int(11) NOT NULL DEFAULT '0',
  `strPhoto` varchar(100) DEFAULT NULL,
  `dtApplied` datetime DEFAULT NULL,
  `tTimeStamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `strReasonForClearance` text,
  `strOtherNotes` text,
  `intClearanceStatus` int(11) DEFAULT NULL,
  `dtFinalised` datetime DEFAULT NULL,
  `intReasonForClearanceID` int(11) DEFAULT '0',
  `intCreatedFrom` int(11) DEFAULT '0',
  `strFilingNumber` varchar(20) DEFAULT '',
  `intClearancePriority` int(11) DEFAULT '0',
  `intAssocTypeID` int(11) DEFAULT '0',
  `intRecStatus` int(11) DEFAULT '0',
  `intPlayerActive` tinyint(4) DEFAULT '0',
  `intCoachActive` tinyint(4) DEFAULT '0',
  `intMthOfficialActive` tinyint(4) DEFAULT '0',
  `dtPermitFrom` datetime DEFAULT NULL,
  `dtPermitTo` datetime DEFAULT NULL,
  `strReason` varchar(100) DEFAULT NULL,
  `intClearanceYear` int(11) DEFAULT '0',
  `dtDue` date DEFAULT NULL,
  `dtReminder` date DEFAULT NULL,
  `intPermitType` tinyint(4) DEFAULT '0',
  `intHasAgent` tinyint(4) DEFAULT '0',
  `strAgentFirstname` varchar(50) DEFAULT '',
  `strAgentSurname` varchar(50) DEFAULT '',
  `strAgentNationality` varchar(50) DEFAULT '',
  `strAgentLicenseNum` varchar(50) DEFAULT '',
  `strAgencyName` varchar(50) DEFAULT '',
  `strAgencyEmail` varchar(100) DEFAULT '',
  PRIMARY KEY (`intClearanceID`),
  KEY `index_intPersonID` (`intPersonID`),
  KEY `index_intDestinationEntityID` (`intDestinationEntityID`),
  KEY `index_intSourceEntityID` (`intSourceEntityID`),
  KEY `index_intDestinationAssocID` (`intDestinationAssocID`),
  KEY `index_intSourceAssocID` (`intSourceAssocID`),
  KEY `index_intRealmID` (`intRealmID`),
  KEY `index_intClearanceStatus` (`intClearanceStatus`),
  KEY `index_intCurrentPathID` (`intCurrentPathID`),
  KEY `index_intClearanceYear` (`intClearanceYear`),
  KEY `index_FromYear` (`intCreatedFrom`,`intClearanceYear`),
  KEY `index_dtApplied` (`dtApplied`)
) DEFAULT CHARSET=utf8;
