DROP TABLE IF EXISTS `tblEntity`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tblEntity` (
  `intEntityID` int(11) NOT NULL AUTO_INCREMENT,
    intEntityLevel INT DEFAULT 0,
    intRealmID INT DEFAULT 0,
    intEntityType INT DEFAULT 0,
  `intRecStatus` tinyint(4) DEFAULT '1',
  `strName` varchar(50) NOT NULL DEFAULT '',
  `strAbbrev` varchar(10) DEFAULT NULL,
  `strClubNo` varchar(50) DEFAULT NULL,
  `strContact` varchar(50) DEFAULT NULL,
  `strAddress1` varchar(50) DEFAULT NULL,
  `strAddress2` varchar(50) DEFAULT NULL,
  `strSuburb` varchar(50) DEFAULT NULL,
  `strPostalCode` varchar(15) DEFAULT NULL,
  `strState` varchar(20) DEFAULT NULL,
  `strPhone` varchar(20) DEFAULT NULL,
  `strFax` varchar(20) DEFAULT NULL,
  `strEmail` varchar(200) DEFAULT NULL,
  `strExtKey` varchar(20) DEFAULT NULL,
  `strCountry` varchar(50) DEFAULT NULL,
  `tTimeStamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `strIncNo` varchar(50) DEFAULT NULL,
  `strBusinessNo` varchar(50) DEFAULT NULL,
  `intAgeTypeID` int(11) DEFAULT NULL,
  `intClubTypeID` int(11) DEFAULT NULL,
  `strGroundName` varchar(50) DEFAULT NULL,
  `strGroundAddress` varchar(50) DEFAULT NULL,
  `strGroundSuburb` varchar(20) DEFAULT NULL,
  `strGroundPostalCode` varchar(10) DEFAULT NULL,
  `strColours` varchar(25) DEFAULT NULL,
  `strNotes` text,
  `strClubCustomCheckBox1` char(2) DEFAULT NULL,
  `strClubCustomCheckBox2` char(2) DEFAULT NULL,
  `strContactTitle` varchar(50) DEFAULT NULL,
  `strContactTitle2` varchar(50) DEFAULT NULL,
  `strContactName2` varchar(100) DEFAULT NULL,
  `strContactEmail2` varchar(200) DEFAULT NULL,
  `strContactPhone2` varchar(50) DEFAULT NULL,
  `strContactTitle3` varchar(50) DEFAULT NULL,
  `strContactName3` varchar(100) DEFAULT NULL,
  `strContactEmail3` varchar(200) DEFAULT NULL,
  `strContactPhone3` varchar(50) DEFAULT NULL,
  `strWebURL` varchar(200) DEFAULT '',
  `intExcludeClubChampionships` tinyint(4) DEFAULT '0',
  `intApprovePayment` tinyint(4) DEFAULT '0',
  `intClubFeeAllocationType` tinyint(4) DEFAULT '0',
  `strLGA` varchar(250) DEFAULT NULL,
  `dtUpdated` datetime DEFAULT NULL,
  `strDevelRegion` varchar(250) DEFAULT NULL,
  `strClubZone` varchar(250) DEFAULT NULL,
  `intSPAgreement_NewEntity` tinyint(4) DEFAULT '1',
  `intClubCategoryID` int(11) DEFAULT '0',
  `intGoodSport` int(11) DEFAULT NULL,
  PRIMARY KEY (`intEntityID`),
  KEY `index_strName` (`strName`),
  KEY `index_intRealmID` (`intRealmID`),
  KEY `index_intEntityLevel` (`intEntityLevel`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

