DROP TABLE tblMember;
 
CREATE TABLE tblMember (
    intMemberID int(11) NOT NULL AUTO_INCREMENT,
    intRealmID int(11) NOT NULL DEFAULT 0,
    strExtKey varchar(20) NOT NULL DEFAULT ,
    strMemberNo varchar(15) NOT NULL DEFAULT ,
    strNationalNum varchar(30) DEFAULT '',
    intFIFAId INT(20) default 0,

    intStatus INT DEFAULT 0,

    strLocalISOCode varchar(10) default '',
    strLocalTitle varchar(30) DEFAULT '',
    strLocalFirstname varchar(50) DEFAULT '',
    strLocalMiddlename varchar(50) DEFAULT '',
    strLocalSurname varchar(150) DEFAULT '',
    strLocalSurname2 varchar(150) DEFAULT '',

    strLatinTitle varchar(30) DEFAULT '',
    strLatinFirstname varchar(50) DEFAULT '',
    strLatinMiddlename varchar(50) DEFAULT '',
    strLatinSurname varchar(150) DEFAULT '',
    strLatinSurname2 varchar(150) DEFAULT '',

    intGender tinyint(4) DEFAULT 0,
    dtDOB date DEFAULT '',
    strISOCountryOfBirth varchar(100) default '',
    strRegionOfBirth varchar(100) default '',
    strPlaceOfBirth varchar(100) default '',

    dtDeath date,

    dtFirstRegistered      date,
    dtLastRegistered        date,
    dtRegisteredUntil      date,



    strAddress1 varchar(100) DEFAULT '',
    strAddress2 varchar(100) DEFAULT '',
    strSuburb varchar(100) DEFAULT '',
    strState varchar(50) DEFAULT '',
    strPostalCode varchar(15) DEFAULT '',
    strISOCountry varchar(50) DEFAULT '',
    strMaidenName varchar(50) DEFAULT '',
    strPhoneHome varchar(30) DEFAULT '',
    strPhoneWork varchar(30) DEFAULT '',
    strPhoneMobile varchar(30) DEFAULT '',
    strFax varchar(30) DEFAULT '',
    strPager varchar(30) DEFAULT '',
    strEmail varchar(200) DEFAULT '',
    dtLastUpdate datetime DEFAULT '',
    intEthnicityID int(11) DEFAULT '',
    strNotes text,
    strPhotoFilename varchar(100) DEFAULT '',
    strCityOfResidence varchar(50) DEFAULT '',
    strPassportNo varchar(50) DEFAULT '',
    strPassportNationality varchar(50) DEFAULT '',
    dtPassportExpiry date DEFAULT '',
    strEmergContName varchar(100) DEFAULT '',
    strEmergContRel varchar(100) DEFAULT '',
    strEmergContNo varchar(100) DEFAULT '',
    strEyeColour varchar(30) DEFAULT '',
    strHairColour varchar(30) DEFAULT '',
    strHeight varchar(20) DEFAULT '',
    strWeight varchar(20) DEFAULT '',
    strP1FName varchar(50) DEFAULT '',
    strP1SName varchar(50) DEFAULT '',
    strP2FName varchar(50) DEFAULT '',
    strP2SName varchar(50) DEFAULT '',
    strBirthCertNo varchar(50) DEFAULT '',
    strHealthCareNo varchar(50) DEFAULT '',
    intIdentTypeID int(11) DEFAULT '',
    strIdentNum varchar(20) DEFAULT '',
    strNatCustomStr1 varchar(50) DEFAULT '',
    strNatCustomStr2 varchar(50) DEFAULT '',
    strNatCustomStr3 varchar(50) DEFAULT '',
    strNatCustomStr4 varchar(50) DEFAULT '',
    strNatCustomStr5 varchar(50) DEFAULT '',
    strNatCustomStr6 varchar(50) DEFAULT '',
    strNatCustomStr7 varchar(30) DEFAULT '',
    strNatCustomStr8 varchar(30) DEFAULT '',
    dblNatCustomDbl1 double DEFAULT 0,
    dblNatCustomDbl2 double DEFAULT 0,
    dblNatCustomDbl3 double DEFAULT 0,
    dblNatCustomDbl4 double DEFAULT 0,
    dtNatCustomDt1 date DEFAULT '',
    dtNatCustomDt2 date DEFAULT '',
    dtSuspendedUntil date DEFAULT '',
    intPlayer tinyint(4) DEFAULT 0,
    intCoach tinyint(4) DEFAULT 0,
    intUmpire tinyint(4) DEFAULT 0,
    intOfficial tinyint(4) DEFAULT 0,
    intMisc tinyint(4) DEFAULT 0,
    intPhoto tinyint(4) DEFAULT 0,
    tTimeStamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    dtPoliceCheck date DEFAULT '',
    dtPoliceCheckExp date DEFAULT '',
    strPoliceCheckRef varchar(30) DEFAULT '',
    intNatCustomLU1 int(11) DEFAULT '',
    intNatCustomLU2 int(11) DEFAULT '',
    intNatCustomLU3 int(11) DEFAULT '',
    strP1Email varchar(250) DEFAULT ,
    strP2Email varchar(250) DEFAULT ,
    strP1Phone varchar(30) DEFAULT ,
    strP2Phone varchar(30) DEFAULT ,
    intMedicalConditions tinyint(4) DEFAULT 0,
    intAllergies tinyint(4) DEFAULT 0,
    strMedicalNotes text,
    intAllowMedicalTreatment tinyint(4) DEFAULT 0,
    intConsentSignatureSighted tinyint(4) DEFAULT 0,
    dtCreatedOnline date DEFAULT '',
    intCreatedFrom int(11) DEFAULT 0,
    strEmergContNo2 varchar(100) DEFAULT ,
    strP1Salutation varchar(30) DEFAULT ,
    strP2Salutation varchar(30) DEFAULT ,
    intP1Gender tinyint(4) DEFAULT 0,
    intP2Gender tinyint(4) DEFAULT 0,
    strP1Phone2 varchar(30) DEFAULT ,
    strP2Phone2 varchar(30) DEFAULT ,
    strP1PhoneMobile varchar(30) DEFAULT ,
    strP2PhoneMobile varchar(30) DEFAULT ,
    strP1Email2 varchar(250) DEFAULT ,
    strP2Email2 varchar(250) DEFAULT ,
    intDefaulter tinyint(4) DEFAULT 0,
    intVolunteer tinyint(4) DEFAULT 0,
    strNatCustomStr9 varchar(50) DEFAULT ,
    strNatCustomStr10 varchar(50) DEFAULT ,
    strNatCustomStr11 varchar(50) DEFAULT ,
    strNatCustomStr12 varchar(50) DEFAULT ,
    strNatCustomStr13 varchar(50) DEFAULT ,
    strNatCustomStr14 varchar(50) DEFAULT ,
    strNatCustomStr15 varchar(50) DEFAULT ,
    dblNatCustomDbl5 double DEFAULT 0,
    dblNatCustomDbl6 double DEFAULT 0,
    dblNatCustomDbl7 double DEFAULT 0,
    dblNatCustomDbl8 double DEFAULT 0,
    dblNatCustomDbl9 double DEFAULT 0,
    dblNatCustomDbl10 double DEFAULT 0,
    dtNatCustomDt3 date DEFAULT '',
    dtNatCustomDt4 date DEFAULT '',
    dtNatCustomDt5 date DEFAULT '',
    intNatCustomLU4 int(11) DEFAULT 0,
    intNatCustomLU5 int(11) DEFAULT 0,
    intNatCustomLU6 int(11) DEFAULT 0,
    intNatCustomLU7 int(11) DEFAULT 0,
    intNatCustomLU8 int(11) DEFAULT 0,
    intNatCustomLU9 int(11) DEFAULT 0,
    intNatCustomLU10 int(11) DEFAULT 0,
    intNatCustomBool1 tinyint(4) DEFAULT 0,
    intNatCustomBool2 tinyint(4) DEFAULT 0,
    intNatCustomBool3 tinyint(4) DEFAULT 0,
    intNatCustomBool4 tinyint(4) DEFAULT 0,
    intNatCustomBool5 tinyint(4) DEFAULT 0,
    strPreferredName varchar(100) DEFAULT ,
    strPreferredLang varchar(50) DEFAULT ,
    strPassportIssueCountry varchar(50) DEFAULT '',
    strMotherCountry varchar(100) DEFAULT ,
    strFatherCountry varchar(100) DEFAULT ,
    intDeRegister int(11) DEFAULT 0,
    intPhotoUseApproval tinyint(4) DEFAULT 0,
      
  PRIMARY KEY (intMemberID),
  KEY index_strMemberNo (strMemberNo),
  KEY index_intStatus (intStatus),
  KEY index_strExtKey (strExtKey),
  KEY index_strLocalSurname (strLocalSurname),
  KEY index_strLocalFirstname (strLocalFirstname),
  KEY index_dtDOB (dtDOB),
  KEY index_intGender (intGender),
  KEY index_strNationalNum (strNationalNum),
  KEY index_dtLastUpdate (dtLastUpdate),
  KEY index_intRealmID (intRealmID),
  KEY index_RealmStatus (intRealmID,intStatus),
  KEY index_RealmNameDOB (intRealmID,strSurname,strFirstname,dtDOB),
  KEY index_RealmEmail (intRealmID,strEmail),
  KEY index_RealmNatNumMID (intRealmID,strNationalNum,intMemberID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
    

