DROP TABLE tblMember;
 
CREATE TABLE `tblMember` (
  `intMemberID` int(11) NOT NULL AUTO_INCREMENT,
  `strExtKey` varchar(20) NOT NULL DEFAULT '',
  `strMemberNo` varchar(15) NOT NULL DEFAULT '',
  `strFirstname` varchar(50) DEFAULT NULL,
  `strMiddlename` varchar(50) DEFAULT NULL,
  `strSurname` varchar(50) DEFAULT NULL,

      ## MA FIELDS
        intRecStatus        INT DEFAULT 0,
        dtFirstRegistered      date,
        dtLastRegistered        date,
        curMemberFinBal        decimal(12,2)  DEFAULT 0.00,
        dtRegisteredUntil      date,



  `strAddress1` varchar(100) DEFAULT NULL,
  `strAddress2` varchar(100) DEFAULT NULL,
  `strSuburb` varchar(100) DEFAULT NULL,
  `strState` varchar(50) DEFAULT NULL,
  `strPostalCode` varchar(15) DEFAULT NULL,
  `strCountry` varchar(50) DEFAULT NULL,
  `strSalutation` varchar(30) DEFAULT NULL,
  `dtDOB` date DEFAULT NULL,
  `intGender` tinyint(4) DEFAULT NULL,
  `strMaidenName` varchar(50) DEFAULT NULL,
  `strPhoneHome` varchar(30) DEFAULT NULL,
  `strPhoneWork` varchar(30) DEFAULT NULL,
  `strPhoneMobile` varchar(30) DEFAULT NULL,
  `strFax` varchar(30) DEFAULT NULL,
  `strPager` varchar(30) DEFAULT NULL,
  `strEmail` varchar(200) DEFAULT NULL,
  `dtLastUpdate` datetime DEFAULT NULL,
  `intEthnicityID` int(11) DEFAULT NULL,
  `intOccupationID` int(11) DEFAULT NULL,
  `intStatus` int(11) NOT NULL DEFAULT '1',
  `strNotes` text,
  `strPhotoFilename` varchar(100) DEFAULT NULL,
  `strPlaceofBirth` varchar(50) DEFAULT NULL,
  `strCountryOfBirth` varchar(50) DEFAULT NULL,
  `strCityOfResidence` varchar(50) DEFAULT NULL,
  `strPassportNo` varchar(50) DEFAULT NULL,
  `strPassportNationality` varchar(50) DEFAULT NULL,
  `dtPassportExpiry` date DEFAULT NULL,
  `strEmergContName` varchar(100) DEFAULT NULL,
  `strEmergContRel` varchar(100) DEFAULT NULL,
  `strEmergContNo` varchar(100) DEFAULT NULL,
  `strEyeColour` varchar(30) DEFAULT NULL,
  `strHairColour` varchar(30) DEFAULT NULL,
  `strHeight` varchar(20) DEFAULT NULL,
  `strWeight` varchar(20) DEFAULT NULL,
  `intDeceased` tinyint(4) DEFAULT NULL,
  `strP1FName` varchar(50) DEFAULT NULL,
  `strP1SName` varchar(50) DEFAULT NULL,
  `strP2FName` varchar(50) DEFAULT NULL,
  `strP2SName` varchar(50) DEFAULT NULL,
  `strBirthCertNo` varchar(50) DEFAULT NULL,
  `strHealthCareNo` varchar(50) DEFAULT NULL,
  `intIdentTypeID` int(11) DEFAULT NULL,
  `strIdentNum` varchar(20) DEFAULT NULL,
  `strNatCustomStr1` varchar(50) DEFAULT NULL,
  `strNatCustomStr2` varchar(50) DEFAULT NULL,
  `strNatCustomStr3` varchar(50) DEFAULT NULL,
  `strNatCustomStr4` varchar(50) DEFAULT NULL,
  `strNatCustomStr5` varchar(50) DEFAULT NULL,
  `strNatCustomStr6` varchar(50) DEFAULT NULL,
  `strNatCustomStr7` varchar(30) DEFAULT NULL,
  `strNatCustomStr8` varchar(30) DEFAULT NULL,
  `dblNatCustomDbl1` double DEFAULT '0',
  `dblNatCustomDbl2` double DEFAULT '0',
  `dblNatCustomDbl3` double DEFAULT '0',
  `dblNatCustomDbl4` double DEFAULT '0',
  `dtNatCustomDt1` date DEFAULT NULL,
  `dtNatCustomDt2` date DEFAULT NULL,
  `strNationalNum` varchar(30) DEFAULT NULL,
  `dtSuspendedUntil` date DEFAULT NULL,
  `intPlayer` tinyint(4) DEFAULT '0',
    `intCoach` tinyint(4) DEFAULT '0',
  `intUmpire` tinyint(4) DEFAULT '0',
  `intOfficial` tinyint(4) DEFAULT '0',
  `intMisc` tinyint(4) DEFAULT '0',
  `intPhoto` tinyint(4) DEFAULT '0',
  `tTimeStamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `intRealmID` int(11) NOT NULL DEFAULT '0',
  `dtPoliceCheck` date DEFAULT NULL,
  `dtPoliceCheckExp` date DEFAULT NULL,
  `strPoliceCheckRef` varchar(30) DEFAULT NULL,
  `intFavStateTeamID` int(11) DEFAULT '0',
  `intFavNationalTeamID` int(11) DEFAULT '0',
  `intNatCustomLU1` int(11) DEFAULT NULL,
  `intNatCustomLU2` int(11) DEFAULT NULL,
  `intNatCustomLU3` int(11) DEFAULT NULL,
  `intSchoolID` int(11) DEFAULT '0',
  `intGradeID` int(11) DEFAULT '0',
  `intHowFoundOutID` int(11) DEFAULT '0',
  `strP1Email` varchar(250) DEFAULT '',
  `strP2Email` varchar(250) DEFAULT '',
  `strP1Phone` varchar(30) DEFAULT '',
  `strP2Phone` varchar(30) DEFAULT '',
  `intP1AssistAreaID` int(11) DEFAULT '0',
  `intP2AssistAreaID` int(11) DEFAULT '0',
  `intMedicalConditions` tinyint(4) DEFAULT '0',
  `intAllergies` tinyint(4) DEFAULT '0',
  `strMedicalNotes` text,
  `intAllowMedicalTreatment` tinyint(4) DEFAULT '0',
  `intConsentSignatureSighted` tinyint(4) DEFAULT '0',
  `dtCreatedOnline` date DEFAULT NULL,
  `intCreatedFrom` int(11) DEFAULT '0',
  `intFavNationalTeamMember` tinyint(4) DEFAULT '0',
  `intAttendSportCount` int(11) DEFAULT '0',
  `intWatchSportHowOftenID` int(11) DEFAULT '0',
  `strEmergContNo2` varchar(100) DEFAULT '',
  `strP1Salutation` varchar(30) DEFAULT '',
  `strP2Salutation` varchar(30) DEFAULT '',
  `intP1Gender` tinyint(4) DEFAULT '0',
  `intP2Gender` tinyint(4) DEFAULT '0',
  `strP1Phone2` varchar(30) DEFAULT '',
  `strP2Phone2` varchar(30) DEFAULT '',
  `strP1PhoneMobile` varchar(30) DEFAULT '',
  `strP2PhoneMobile` varchar(30) DEFAULT '',
  `strP1Email2` varchar(250) DEFAULT '',
  `strP2Email2` varchar(250) DEFAULT '',
  `intDefaulter` tinyint(4) DEFAULT '0',
  `intVolunteer` tinyint(4) DEFAULT '0',
  `strNatCustomStr9` varchar(50) DEFAULT '',
  `strNatCustomStr10` varchar(50) DEFAULT '',
  `strNatCustomStr11` varchar(50) DEFAULT '',
  `strNatCustomStr12` varchar(50) DEFAULT '',
  `strNatCustomStr13` varchar(50) DEFAULT '',
  `strNatCustomStr14` varchar(50) DEFAULT '',
  `strNatCustomStr15` varchar(50) DEFAULT '',
  `dblNatCustomDbl5` double DEFAULT '0',
  `dblNatCustomDbl6` double DEFAULT '0',
  `dblNatCustomDbl7` double DEFAULT '0',
  `dblNatCustomDbl8` double DEFAULT '0',
  `dblNatCustomDbl9` double DEFAULT '0',
  `dblNatCustomDbl10` double DEFAULT '0',
  `dtNatCustomDt3` date DEFAULT NULL,
  `dtNatCustomDt4` date DEFAULT NULL,
  `dtNatCustomDt5` date DEFAULT NULL,
  `intNatCustomLU4` int(11) DEFAULT '0',
  `intNatCustomLU5` int(11) DEFAULT '0',
  `intNatCustomLU6` int(11) DEFAULT '0',
  `intNatCustomLU7` int(11) DEFAULT '0',
  `intNatCustomLU8` int(11) DEFAULT '0',
  `intNatCustomLU9` int(11) DEFAULT '0',
  `intNatCustomLU10` int(11) DEFAULT '0',
    `intNatCustomBool1` tinyint(4) DEFAULT '0',
  `intNatCustomBool2` tinyint(4) DEFAULT '0',
  `intNatCustomBool3` tinyint(4) DEFAULT '0',
  `intNatCustomBool4` tinyint(4) DEFAULT '0',
  `intNatCustomBool5` tinyint(4) DEFAULT '0',
  `strPreferredName` varchar(100) DEFAULT '',
  `strEmail2` varchar(200) DEFAULT '',
  `strPreferredLang` varchar(50) DEFAULT '',
  `strPassportIssueCountry` varchar(50) DEFAULT NULL,
  `strUmpirePassword` varchar(10) DEFAULT NULL,
  `strMotherCountry` varchar(100) DEFAULT '',
  `strFatherCountry` varchar(100) DEFAULT '',
  `intDeRegister` int(11) DEFAULT '0',
  `intPhotoUseApproval` tinyint(4) DEFAULT '0',
  `intSINGFIX_ClubID` int(11) DEFAULT '0',
  `strSING_EXT` varchar(15) DEFAULT '',
  
  PRIMARY KEY (`intMemberID`),
  KEY `index_strMemberNo` (`strMemberNo`),
  KEY `index_intStatus` (`intStatus`),
  KEY `index_strExtKey` (`strExtKey`),
  KEY `index_strSurname` (`strSurname`),
  KEY `index_strFirstname` (`strFirstname`),
  KEY `index_dtDOB` (`dtDOB`),
  KEY `index_intGender` (`intGender`),
  KEY `index_strNationalNum` (`strNationalNum`),
  KEY `index_dtLastUpdate` (`dtLastUpdate`),
  KEY `index_intRealmID` (`intRealmID`),
  KEY `index_RealmStatus` (`intRealmID`,`intStatus`),
  KEY `index_RealmNameDOB` (`intRealmID`,`strSurname`,`strFirstname`,`dtDOB`),
  KEY `index_RealmEmail` (`intRealmID`,`strEmail`),
  KEY `index_RealmNatNumMID` (`intRealmID`,`strNationalNum`,`intMemberID`),
  KEY `index_strUmpirePassword` (`strUmpirePassword`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
    

