DROP TABLE IF EXISTS tblTransLog;
CREATE TABLE tblTransLog (
    intLogID int(11) NOT NULL auto_increment,
    dtLog datetime default NULL,
    intAmount decimal(16,2) default 0.00,
    strTXN varchar(200) default NULL,
	strOnlinePayReference varchar(100) default '',
    strResponseCode varchar(10) default NULL,
    strGatewayResponseCode varchar(10) default '',
    strResponseText varchar(100) default NULL,
    strComments text,
    intPaymentType int(11) default NULL,
    strBSB varchar(50) default NULL,
    strBank varchar(100) default NULL,
    strAccountName varchar(100) default NULL,
    strAccountNum varchar(100) default NULL,
    intRealmID int(11) default NULL,
    intCurrencyID int(11) default '0',
    strReceiptRef varchar(100) default NULL,
    intStatus tinyint(4) default '0',
    intPartialPayment tinyint(4) default '0',
    tTimeStamp TIMESTAMP,
    dtSettlement date,
    intEntityPaymentID INT default 0,
    intPaymentConfigID INT default 0,
    strAuthID varchar(50) default '',
    strText varchar(150) default '',
    strOtherRef1 varchar(100) default '',
    strOtherRef2 varchar(100) default '',
    strOtherRef3 varchar(100) default '',
    strOtherRef4 varchar(100) default '',
    strOtherRef5 varchar(100) default '',
    curGatewayFees decimal(16,2) default 0.00,
    intRegoFormID INT default 0,
    intExportOK TINYINT default 0,
    intSWMPaymentAuthLevel TINYINT default 0,
    strSessionKey varchar(40) default '',
    intSentToGateway TINYINT default 0,
    intPaymentGatewayResponded TINYINT default 0,
    intCheckOnceDaily TINYINT default 0,
    dtTLCreated datetime default '0000-00-00 00:00:00',
  PRIMARY KEY  (intLogID),
  KEY index_realmID (intRealmID),
  KEY index_paymentType (intPaymentType),
  KEY intEntityPaymentID(intEntityPaymentID),
  KEY intCurrencyID (intCurrencyID),
  KEY intStatus (intStatus),
  KEY intPartialPayment (intPartialPayment)
) DEFAULT CHARSET=utf8;

