DROP TABLE tblClearance;
#
CREATE table tblClearance (
	intClearanceID     				INT NOT NULL AUTO_INCREMENT,
	intMemberID		INT(11) NOT NULL DEFAULT 0,
	intDestinationClubID		INT(11) NOT NULL DEFAULT 0,
	strDestinationClubName	VARCHAR(100),
	intSourceClubID			INT(11) NOT NULL DEFAULT 0,
	strSourceClubName	VARCHAR(100),
	intDestinationAssocID		INT(11) NOT NULL DEFAULT 0,
	strDestinationAssocName	VARCHAR(100),
	intSourceAssocID			INT(11) NOT NULL DEFAULT 0,
	strSourceAssocName	VARCHAR(100),
	intRealmID			INT(11) NOT NULL DEFAULT 0,
	intCurrentPathID			INT(11) NOT NULL DEFAULT 0,
	strPhoto			VARCHAR(100),
	dtApplied			DATETIME,
	tTimeStamp			TIMESTAMP,
	strReasonForClearance		TEXT,
	strOtherNotes	TEXT,
	intClearanceStatus		INTEGER,
	dtFinalised	DATETIME,
	intReasonForClearanceID INT(11) DEFAULT 0,
	intCreatedFrom	INT(11) DEFAULT 0,
	strFilingNumber	varchar(20) default '',
	intClearancePriority INT(11) DEFAULT 0,
	intAssocTypeID	INT(11) DEFAULT 0,
	intRecStatus	INT(11) DEFAULT 0,
	intPlayerActive tinyint DEFAULT 0,
    	intCoachActive tinyint DEFAULT 0,
    	intMthOfficialActive tinyint DEFAULT 0,
	dtPermitFrom	DATETIME,
	dtPermitTo	DATETIME,

PRIMARY KEY (intClearanceID),
	KEY index_intMemberID(intMemberID),
	KEY index_intDestinationClubID(intDestinationClubID),
	KEY index_intSourceClubID(intSourceClubID),
	KEY index_intDestinationAssocID(intDestinationAssocID),
	KEY index_intSourceAssocID(intSourceAssocID),
	KEY index_intRealmID(intRealmID),
	KEY index_intClearanceStatus(intClearanceStatus),
	KEY index_intCurrentPathID(intCurrentPathID)
);
 
