ALTER TABLE `tblEntityIdentifier` 
ADD COLUMN `dtAdded` DATETIME NULL AFTER `strDescription`,
ADD COLUMN `dtLastUpdated` DATETIME NULL AFTER `dtAdded`,
ADD COLUMN `tTimestamp` VARCHAR(45) NULL DEFAULT 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP' AFTER `dtLastUpdated`,
ADD COLUMN `intStatus` INT NULL DEFAULT 1 AFTER `tTimestamp`;
