ALTER TABLE `tblDocuments` 
ADD COLUMN `dtAdded` DATETIME NULL AFTER `intUploadFileID`,
ADD COLUMN `dtLastUpdated` DATETIME NULL AFTER `dtAdded`,
ADD COLUMN `tTimeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `dtLastUpdated`;
