ALTER TABLE `tblEntity` ADD COLUMN `strCity` VARCHAR(100) NULL DEFAULT NULL AFTER `strTown`;
ALTER TABLE `tblEntity` ADD COLUMN `strState` VARCHAR(100) NULL DEFAULT NULL AFTER `strCity`;
ALTER TABLE `tblEntity` ADD COLUMN `strContactCity` VARCHAR(100) NULL DEFAULT NULL AFTER `strContactPhone`;
ALTER TABLE `tblEntity` ADD COLUMN `strContactISOCountry` VARCHAR(10) NULL DEFAULT NULL AFTER `strContactCity`;
