DELETE FROM tblLocalTranslations WHERE strType='PRODUCT' AND intID>=200;
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 200 ,"fi_FI","Jalkapallopelipassi 1996 tai aiemmin synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 201 ,"fi_FI","Jalkapallopelipassi 1997-2004 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 202 ,"fi_FI","Jalkapallopelipassi 2005-2016 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 203 ,"fi_FI","Jalkapalloharrastepassi 1996 tai aiemmin synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 204 ,"fi_FI","Jalkapallokorttelipassi 1997-2004 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 205 ,"fi_FI","Jalkapallokorttelipassi  2005-2016 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 206 ,"fi_FI","Jalkapallopelipassi 1996 tai aiemmin synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 207 ,"fi_FI","Jalkapallopelipassi 1997-2004 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 208 ,"fi_FI","Jalkapallopelipassi 2005-2016 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 209 ,"fi_FI","Jalkapalloharrastepassi 1996 tai aiemmin synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 210 ,"fi_FI","Jalkapallokorttelipassi 1997-2004 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 211 ,"fi_FI","Jalkapallokorttelipassi  2005-2016 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 212 ,"fi_FI","Futsalpelipassi 1996 tai aiemmin synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 213 ,"fi_FI","Futsalpelipassi 1997-2004 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 214 ,"fi_FI","Futsalpelipassi 2005-2016 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 215 ,"fi_FI","Futsalharrastepassi 1996 tai aiemmin synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 216 ,"fi_FI","Futsalkorttelipassi 1997-2004 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 217 ,"fi_FI","Futsalkorttelipassi  2005-2016 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 218 ,"fi_FI","Futsalpelipassi 1996 tai aiemmin synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 219 ,"fi_FI","Futsalpelipassi 1997-2004 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 220 ,"fi_FI","Futsalpelipassi 2005-2016 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 221 ,"fi_FI","Futsalharrastepassi 1996 tai aiemmin synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 222 ,"fi_FI","Futsalkorttelipassi 1997-2004 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 223 ,"fi_FI","Futsalkorttelipassi  2005-2016 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 224 ,"fi_FI","UEFA valmentajakorttimaksu, 3 vuotta");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 225 ,"fi_FI","V50 Erotuomarivakuutus");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 226 ,"fi_FI","V50 Erotuomarivakuutus");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 227 ,"fi_FI","V10 Laaja vakuutusturva 1946-1996 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 228 ,"fi_FI","V11 Suppea vakuutusturva 1946-1996 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 229 ,"fi_FI","V12 Laaja vakuutusturva 1946-1996 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 230 ,"fi_FI","V13 Suppea vakuutusturva 1946-1996 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 231 ,"fi_FI","V20 Vakuutusturva 1997-2000 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 232 ,"fi_FI","V21 Vakuutusturva 2001-2004 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 233 ,"fi_FI","V22 Vakuutusturva 2005-2016 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 234 ,"fi_FI","V30 Korttelipassivakuutus 1997-2004 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 235 ,"fi_FI","V31 Korttelipassivakuutus  2005-2016 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 236 ,"fi_FI","V40 Harrastepassivakuutus 1946-1996 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 237 ,"fi_FI","VK1 Korotus edellyttäen perusturvan voimassaoloa, V10-V12");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 238 ,"fi_FI","VK2 Korotus edellyttäen perusturvan voimassaoloa, V11-V10");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 239 ,"fi_FI","VK3 Korotus edellyttäen perusturvan voimassaoloa, V11-V13");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 240 ,"fi_FI","VK4 Korotus edellyttäen perusturvan voimassaoloa, V13-V12");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 241 ,"fi_FI","VK5 Korotus edellyttäen perusturvan voimassaoloa, V11-V12");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 242 ,"fi_FI","V10 Laaja vakuutusturva 1946-1996 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 243 ,"fi_FI","V11 Suppea vakuutusturva 1946-1996 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 244 ,"fi_FI","V12 Laaja vakuutusturva 1946-1996 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 245 ,"fi_FI","V13 Suppea vakuutusturva 1946-1996 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 246 ,"fi_FI","V20 Vakuutusturva 1997-2000 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 247 ,"fi_FI","V21 Vakuutusturva 2001-2004 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 248 ,"fi_FI","V22 Vakuutusturva 2005-2016 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 249 ,"fi_FI","V30 Korttelipassivakuutus 1997-2004 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 250 ,"fi_FI","V31 Korttelipassivakuutus  2005-2016 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 251 ,"fi_FI","V40 Harrastepassivakuutus 1946-1996 synt.");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 252 ,"fi_FI","VK1 Korotus edellyttäen perusturvan voimassaoloa, V10-V12");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 253 ,"fi_FI","VK2 Korotus edellyttäen perusturvan voimassaoloa, V11-V10");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 254 ,"fi_FI","VK3 Korotus edellyttäen perusturvan voimassaoloa, V11-V13");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 255 ,"fi_FI","VK4 Korotus edellyttäen perusturvan voimassaoloa, V13-V12");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 256 ,"fi_FI","VK5 Korotus edellyttäen perusturvan voimassaoloa, V11-V12");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 257 ,"fi_FI","UEFA valmentajakorttimaksu, 3 vuotta");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 258 ,"fi_FI","Edustusoikeuden rekisteröintimaksu - Ammattilainen, jalkapallo");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 259 ,"fi_FI","Edustusoikeuden rekisteröintimaksu - Amatööri sopimuksella, jalkapallo");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 260 ,"fi_FI","Edustusoikeuden rekisteröintimaksu - Amatööri synt. 1996 tai aikaisemmin, jalkapallo");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 261 ,"fi_FI","Edustusoikeuden rekisteröintimaksu - Amatööri synt. 1997-2004, jalkapallo");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 262 ,"fi_FI","Edustusoikeuden rekisteröintimaksu - Amatööri synt. 2005 tai myöhemmin, jalkapallo");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 263 ,"fi_FI","Edustusoikeuden rekisteröinti - Harraste, jalkapallo");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 264 ,"fi_FI","Edustusoikeuden rekisteröinti - Ei-aktiivinen, jalkapallo");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 265 ,"fi_FI","Kansainvälisen edustusoikeuden rekisteröintimaksu - Ammattilainen, jalkapallo");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 266 ,"fi_FI","Kansainvälisen edustusoikeuden rekisteröintimaksu - Amatööri sopimuksella, jalkapallo");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 267 ,"fi_FI","Kansainvälisen edustusoikeuden rekisteröintimaksu - Amatööri, jalkapallo");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 268 ,"fi_FI","Edustusoikeuden rekisteröintimaksu - Ammattilainen, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 269 ,"fi_FI","Edustusoikeuden rekisteröintimaksu - Amatööri sopimuksella, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 270 ,"fi_FI","Edustusoikeuden rekisteröintimaksu - Amatööri synt. 1996 tai aikaisemmin, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 271 ,"fi_FI","Edustusoikeuden rekisteröintimaksu - Amatööri synt. 1997-2004, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 272 ,"fi_FI","Edustusoikeuden rekisteröintimaksu - Amatööri synt. 2005 tai myöhemmin, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 273 ,"fi_FI","Edustusoikeuden rekisteröinti - Harraste, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 274 ,"fi_FI","Edustusoikeuden rekisteröinti - Ei-aktiivinen, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 275 ,"fi_FI","Kansainvälisen edustusoikeuden rekisteröintimaksu - Ammattilainen, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 276 ,"fi_FI","Kansainvälisen edustusoikeuden rekisteröintimaksu - Amatööri sopimuksella, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 277 ,"fi_FI","Kansainvälisen edustusoikeuden rekisteröintimaksu - Amatööri, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 200 ,"sv_SE","Fotbollsspelpass 1996 eller tidigare födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 201 ,"sv_SE","Fotbollsspelpass 1997-2004 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 202 ,"sv_SE","Fotbollsspelpass 2005-2016 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 203 ,"sv_SE","Fotbollshobbypass 1996 eller tidigare födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 204 ,"sv_SE","Fotbollskvarterspass 1997-2004 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 205 ,"sv_SE","Fotbollskvarterspass 2005-2016 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 206 ,"sv_SE","Fotbollsspelpass 1996 eller tidigare födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 207 ,"sv_SE","Fotbollsspelpass 1997-2004 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 208 ,"sv_SE","Fotbollsspelpass 2005-2016 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 209 ,"sv_SE","Fotbollshobbypass 1996 eller tidigare födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 210 ,"sv_SE","Fotbollskvarterspass 1997-2004 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 211 ,"sv_SE","Fotbollskvarterspass 2005-2016 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 212 ,"sv_SE","Futsalspelpass 1996 eller tidigare födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 213 ,"sv_SE","Futsalspelpass 1997-2004 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 214 ,"sv_SE","Futsalspelpass 2005-2016 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 215 ,"sv_SE","Futsalhobbypass 1996 eller tidigare födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 216 ,"sv_SE","Futsalkvarterspass 1997-2004 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 217 ,"sv_SE","Futsalkvarterspass 2005-2016 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 218 ,"sv_SE","Futsalspelpass 1996 eller tidigare födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 219 ,"sv_SE","Futsalspelpass 1997-2004 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 220 ,"sv_SE","Futsalspelpass 2005-2016 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 221 ,"sv_SE","Futsalhobbypass 1996 eller tidigare födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 222 ,"sv_SE","Futsalkvarterspass 1997-2004 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 223 ,"sv_SE","Futsalkvarterspass 2005-2016 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 224 ,"sv_SE","UEFA tränarkortsavgift, 3 år");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 225 ,"sv_SE","V50 Domarförsäkring");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 226 ,"sv_SE","V50 Domarförsäkring");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 227 ,"sv_SE","V10 Omfattande försäkring 1946-1996 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 228 ,"sv_SE","V11 Begränsad försäkring 1946-1996 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 229 ,"sv_SE","V12 Omfattande försäkring 1946-1996 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 230 ,"sv_SE","V13 Begränsad försäkring 1946-1996 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 231 ,"sv_SE","V20 Försäkring 1997-2000 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 232 ,"sv_SE","V21 Försäkring 2001-2004 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 233 ,"sv_SE","V22 Försäkring 2005-2016 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 234 ,"sv_SE","V30 Kvarterspassförsäkring 1997-2004 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 235 ,"sv_SE","V31 Kvarterspassförsäkring 2005-2016 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 236 ,"sv_SE","V40 Hobbypassförsäkring 1946-1996 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 237 ,"sv_SE","VK1 Förhöjning som kräver basförsäkring i kraft, V10-V12");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 238 ,"sv_SE","VK2 Förhöjning som kräver basförsäkring i kraft, V11-V10");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 239 ,"sv_SE","VK3 Förhöjning som kräver basförsäkring i kraft, V11-V13");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 240 ,"sv_SE","VK4 Förhöjning som kräver basförsäkring i kraft, V13-V12");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 241 ,"sv_SE","VK5 Förhöjning som kräver basförsäkring i kraft,V11-V12");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 242 ,"sv_SE","V10 Omfattande försäkring 1946-1996 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 243 ,"sv_SE","V11 Begränsad försäkring 1946-1996 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 244 ,"sv_SE","V12 Omfattande försäkring 1946-1996 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 245 ,"sv_SE","V13 Begränsad försäkring 1946-1996 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 246 ,"sv_SE","V20 Försäkring 1997-2000 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 247 ,"sv_SE","V21 Försäkring 2001-2004 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 248 ,"sv_SE","V22 Försäkring 2005-2016 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 249 ,"sv_SE","V30 Kvarterspassförsäkring 1997-2004 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 250 ,"sv_SE","V31 Kvarterspassförsäkring 2005-2016 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 251 ,"sv_SE","V40 Hobbypassförsäkring 1946-1996 födda");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 252 ,"sv_SE","VK1 Förhöjning som kräver basförsäkring i kraft, V10-V12");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 253 ,"sv_SE","VK2 Förhöjning som kräver basförsäkring i kraft, V11-V10");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 254 ,"sv_SE","VK3 Förhöjning som kräver basförsäkring i kraft, V11-V13");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 255 ,"sv_SE","VK4 Förhöjning som kräver basförsäkring i kraft, V13-V12");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 256 ,"sv_SE","VK5 Förhöjning som kräver basförsäkring i kraft,V11-V12");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 257 ,"sv_SE","UEFA tränarkortsavgift, 3 år");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 258 ,"sv_SE","Representationsrättens registreringsavgift - Professionell, fotboll");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 259 ,"sv_SE","Representationsrättens registreringsavgift - Amatör med kontrakt, fotboll");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 260 ,"sv_SE","Representationsrättens registreringsavgift - Amatör född 1996 eller tidigare, fotboll");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 261 ,"sv_SE","Representationsrättens registreringsavgift - Amatör född 1997-2004, fotboll");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 262 ,"sv_SE","Representationsrättens registreringsavgift - Amatör född 2005 eller senare, fotboll");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 263 ,"sv_SE","Representationsrättens registrering - Hobby, fotboll");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 264 ,"sv_SE","Representationsrättens registrering - Inaktiv, fotboll");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 265 ,"sv_SE","Internationell representationsrätts registreringsavgift - Professionell, fotboll");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 266 ,"sv_SE","Internationell representationsrätts registreringsavgift - Amatör med kontrakt, fotboll");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 267 ,"sv_SE","Internationell representationsrätts registreringsavgift - Amatör, fotboll");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 268 ,"sv_SE","Representationsrättens registreringsavgift - Professionell, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 269 ,"sv_SE","Representationsrättens registreringsavgift - Amatör med kontrakt, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 270 ,"sv_SE","Representationsrättens registreringsavgift - Amatör född 1996 eller tidigare, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 271 ,"sv_SE","Representationsrättens registreringsavgift - Amatör född 1997-2004, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 272 ,"sv_SE","Representationsrättens registreringsavgift - Amatör född 2005 eller senare, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 273 ,"sv_SE","Representationsrättens registrering - Hobby, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 274 ,"sv_SE","Representationsrättens registrering - Inaktiv, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 275 ,"sv_SE","Internationell representationsrätts registreringsavgift - Professionell, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 276 ,"sv_SE","Internationell representationsrätts registreringsavgift - Amatör med kontrakt, futsal");
INSERT INTO tblLocalTranslations (strType, intID, strLocale, strString1) VALUES ('PRODUCT', 277 ,"sv_SE","Internationell representationsrätts registreringsavgift - Amatör, futsal");
